### ISSUE TITLE
Your code does not mavenize correctly, there are no entry points to your jar

### ISSUE THREAD

**Issue by Khalian** [mariosangiorgio/lyrics#5]
In other words, your jar does not have a main defined in it. You just ended up archiving the whole project.

**Comment by mariosangiorgio** [comment]
If you want to submit a pull request I'll be happy to accept it. It's been a long time since I last worked on this project but I'm obviously happy to improve it

**Comment by Khalian** [comment]
Hi Mario

I fixed that but am still not able to run your code. Can you please help me
out with that?

On Fri, Nov 6, 2015 at 7:43 AM, Mario Sangiorgio <notifications@github.com>
wrote:

> If you want to submit a pull request I'll be happy to accept it. It's been
> a long time since I last worked on this project but I'm obviously happy to
> improve it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mariosangiorgio/lyrics/issues/5#issuecomment-154399877>
> .
>



-- 
Arunav Sanyal
Graduate student
M.S Computer Science
Johns Hopkins University

**Comment by Khalian** [comment]
src/main/java/lyrics/libraryExplorer/LibraryExplorer.java

In this file I see a line:-

     URL path = getClass().getResource("/resources/badSentences");

So I am assuming badSentences is a kind of filter to avoid garbage lines while exploring the library. However the code that you have committed does not have badSentences File. Is it generated by some means? If so how would I do that?

**Comment by mariosangiorgio** [comment]
You're right. It was supposed to be a file containing song titles that needs to be skipped.
It should probably live in an external file that the user can control, not in the jar.
For the time being I just removed it. It's going to be empty but that's better than nothing.

**Comment by Khalian** [comment]
Agreed but the problem is your code is not running. Its giving a null
pointer exception (trying to read the resource and failing)

On Wed, Nov 11, 2015 at 3:57 PM, Mario Sangiorgio <notifications@github.com>
wrote:

> You're right. It was supposed to be a file containing song titles that
> needs to be skipped.
> It should probably live in an external file that the user can control, not
> in the jar.
> For the time being I just removed it. It's going to be empty but that's
> better than nothing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mariosangiorgio/lyrics/issues/5#issuecomment-155907517>
> .
>



-- 
Arunav Sanyal
Graduate student
M.S Computer Science
Johns Hopkins University

**Comment by mariosangiorgio** [comment]
I just committed a fix for that
